// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDBIo8uYyXjksCkfA8kQixymrvdEzgx81U',
    appId: '1:221089588903:web:b25b7d22d5d68806361d82',
    messagingSenderId: '221089588903',
    projectId: 'chessprotrainer',
    authDomain: 'chessprotrainer.firebaseapp.com',
    storageBucket: 'chessprotrainer.firebasestorage.app',
    measurementId: 'G-9D3BP5RNN0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD6UAtEYVfcsN9MIB0ns3UkVhx0XKPq048',
    appId: '1:504617755413:android:f5a7c8503f629944feff1c',
    messagingSenderId: '504617755413',
    projectId: 'spotifyunlocked',
    storageBucket: 'spotifyunlocked.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBP46IDvHEzxr8sOy9kqhGUyfto_71xHpY',
    appId: '1:504617755413:ios:02078024050600f8feff1c',
    messagingSenderId: '504617755413',
    projectId: 'spotifyunlocked',
    storageBucket: 'spotifyunlocked.firebasestorage.app',
    iosBundleId: 'com.spotifyunlocked.app.spotifyUnlocked',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBwxMrhFGLbtqTAWmHk8bo1xBGAJgEaVVw',
    appId: '1:221089588903:ios:7452087c587d4a15361d82',
    messagingSenderId: '221089588903',
    projectId: 'chessprotrainer',
    storageBucket: 'chessprotrainer.firebasestorage.app',
    iosBundleId: 'com.spotifyunlocked.app.spotifyUnlocked',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDBIo8uYyXjksCkfA8kQixymrvdEzgx81U',
    appId: '1:221089588903:web:d39e6435fce82367361d82',
    messagingSenderId: '221089588903',
    projectId: 'chessprotrainer',
    authDomain: 'chessprotrainer.firebaseapp.com',
    storageBucket: 'chessprotrainer.firebasestorage.app',
    measurementId: 'G-BWR0C7PKXY',
  );

}