// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD6UAtEYVfcsN9MIB0ns3UkVhx0XKPq048',
    appId: '1:504617755413:web:95f190119e7a29e1feff1c',
    messagingSenderId: '504617755413',
    projectId: 'spotifyunlocked',
    authDomain: 'spotifyunlocked.firebaseapp.com',
    storageBucket: 'spotifyunlocked.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD6UAtEYVfcsN9MIB0ns3UkVhx0XKPq048',
    appId: '1:504617755413:android:35832a7d8571bbcffeff1c',
    messagingSenderId: '504617755413',
    projectId: 'spotifyunlocked',
    storageBucket: 'spotifyunlocked.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBP46IDvHEzxr8sOy9kqhGUyfto_71xHpY',
    appId: '1:504617755413:ios:02078024050600f8feff1c',
    messagingSenderId: '504617755413',
    projectId: 'spotifyunlocked',
    storageBucket: 'spotifyunlocked.firebasestorage.app',
    iosBundleId: 'com.spotifyunlocked',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBP46IDvHEzxr8sOy9kqhGUyfto_71xHpY',
    appId: '1:504617755413:ios:02078024050600f8feff1c',
    messagingSenderId: '504617755413',
    projectId: 'spotifyunlocked',
    storageBucket: 'spotifyunlocked.firebasestorage.app',
    iosBundleId: 'com.spotifyunlocked',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD6UAtEYVfcsN9MIB0ns3UkVhx0XKPq048',
    appId: '1:504617755413:web:95f190119e7a29e1feff1c',
    messagingSenderId: '504617755413',
    projectId: 'spotifyunlocked',
    authDomain: 'spotifyunlocked.firebaseapp.com',
    storageBucket: 'spotifyunlocked.firebasestorage.app',
  );

}