import { useState, useEffect } from 'react'
import defaultAlbums from './data'
import VideoParser from './VideoParser'
import './index.css'

const AUTH_ENDPOINT = "https://accounts.spotify.com/authorize"
const SCOPES = ["playlist-modify-private", "playlist-modify-public"]

function App() {
  const [token, setToken] = useState("")
  const [clientId, setClientId] = useState(window.localStorage.getItem("spotify_client_id") || "")
  const [spotifyUser, setSpotifyUser] = useState(null)
  const [loading, setLoading] = useState(false)
  const [progress, setProgress] = useState(0)
  const [status, setStatus] = useState("")
  const [playlistUrl, setPlaylistUrl] = useState("")
  const [activeTab, setActiveTab] = useState('list')
  const [parsedAlbums, setParsedAlbums] = useState([])

  useEffect(() => {
    const hash = window.location.hash
    let storedToken = window.localStorage.getItem("token")

    if (!storedToken && hash) {
      const tokenParam = hash.substring(1).split("&").find(elem => elem.startsWith("access_token"))
      if (tokenParam) {
        storedToken = tokenParam.split("=")[1]
        window.location.hash = ""
        window.localStorage.setItem("token", storedToken)
      }
    }

    if (storedToken) {
      setToken(storedToken)
      verifyToken(storedToken)
    }
  }, [])

  const verifyToken = async (t) => {
    try {
      const res = await fetch("https://api.spotify.com/v1/me", {
        headers: { Authorization: `Bearer ${t}` }
      })
      if (res.status === 401) {
        // Token expired — clear it
        setToken("")
        window.localStorage.removeItem("token")
        setSpotifyUser(null)
        return
      }
      const data = await res.json()
      setSpotifyUser({ name: data.display_name || data.id, id: data.id, url: data.external_urls?.spotify })
    } catch {
      // Network error — keep token but don't show user
    }
  }

  const saveClientId = (e) => {
    e.preventDefault()
    const id = e.target.clientId.value.trim()
    if (id) {
      setClientId(id)
      window.localStorage.setItem("spotify_client_id", id)
    }
  }

  const logout = () => {
    setToken("")
    window.localStorage.removeItem("token")
  }

  const resetConfig = () => {
    logout()
    setClientId("")
    setSpotifyUser(null)
    setPlaylistUrl("")
    window.localStorage.removeItem("spotify_client_id")
  }

  const createPlaylist = async (albumList, playlistName = "Spectrum Pulse: Top 50 Albums of 2025") => {
    if (!token) return
    setLoading(true)
    setProgress(0)
    setPlaylistUrl("")
    setStatus("Verifying Spotify connection...")

    try {
      // Verify token is still valid first
      const meRes = await fetch("https://api.spotify.com/v1/me", {
        headers: { Authorization: `Bearer ${token}` }
      })
      if (meRes.status === 401) {
        setToken("")
        window.localStorage.removeItem("token")
        setLoading(false)
        alert("Your Spotify session has expired. Please log in again.")
        return
      }
      const user = await meRes.json()

      const trackUris = []
      const notFound = []
      for (let i = 0; i < albumList.length; i++) {
        const { artist, album } = albumList[i]
        setStatus(`[${i + 1}/${albumList.length}] Searching: "${album}" by ${artist}`)

        const searchRes = await fetch(
          `https://api.spotify.com/v1/search?q=album:${encodeURIComponent(album)}%20artist:${encodeURIComponent(artist)}&type=album&limit=1`,
          { headers: { Authorization: `Bearer ${token}` } }
        )
        const searchData = await searchRes.json()

        if (searchData.albums?.items?.length > 0) {
          const albumId = searchData.albums.items[0].id
          const tracksRes = await fetch(`https://api.spotify.com/v1/albums/${albumId}/tracks?limit=1`, {
            headers: { Authorization: `Bearer ${token}` }
          })
          const tracksData = await tracksRes.json()
          if (tracksData.items?.length > 0) {
            trackUris.push(tracksData.items[0].uri)
          }
        } else {
          notFound.push(`${artist} — ${album}`)
        }

        setProgress(((i + 1) / albumList.length) * 80)
      }

      setStatus("Creating playlist on your account...")
      const playlistRes = await fetch(`https://api.spotify.com/v1/users/${user.id}/playlists`, {
        method: "POST",
        headers: { Authorization: `Bearer ${token}`, "Content-Type": "application/json" },
        body: JSON.stringify({
          name: playlistName,
          description: `Generated by MusicFinder — ${trackUris.length} tracks, first song of each album.`,
          public: false
        })
      })
      const playlist = await playlistRes.json()

      if (!playlist.id) throw new Error("Playlist creation failed. Check your Spotify app permissions include playlist-modify.")

      setStatus(`Adding ${trackUris.length} tracks...`)
      await fetch(`https://api.spotify.com/v1/playlists/${playlist.id}/tracks`, {
        method: "POST",
        headers: { Authorization: `Bearer ${token}`, "Content-Type": "application/json" },
        body: JSON.stringify({ uris: trackUris })
      })

      setProgress(100)
      setStatus(`✅ Done! ${trackUris.length} tracks added.${notFound.length > 0 ? ` (${notFound.length} albums not found on Spotify)` : ''}`)
      setPlaylistUrl(playlist.external_urls?.spotify || `https://open.spotify.com/playlist/${playlist.id}`)
      setTimeout(() => setLoading(false), 3000)
    } catch (err) {
      console.error(err)
      setStatus(`❌ Error: ${err.message}`)
      setTimeout(() => setLoading(false), 3000)
    }
  }

  const spotifyAuthSection = (
    <div className="actions">
      {!clientId ? (
        <form className="config-form" onSubmit={saveClientId}>
          <h3>🎵 Connect to Spotify</h3>

          <div className="setup-tabs">
            <div className="setup-option">
              <div className="setup-option-label">✨ New App</div>
              <ol className="setup-steps">
                <li>Go to <a href="https://developer.spotify.com/dashboard" target="_blank" rel="noreferrer">Spotify Developer Dashboard</a></li>
                <li>Click <strong>"Create App"</strong></li>
                <li>Fill in any name/description</li>
                <li>Under <strong>Redirect URIs</strong>, add: <code>{window.location.origin}</code></li>
                <li>Check <strong>"Web API"</strong> and save</li>
                <li>Copy your <strong>Client ID</strong> and paste below</li>
              </ol>
            </div>

            <div className="setup-divider">— or —</div>

            <div className="setup-option">
              <div className="setup-option-label">✏️ Edit Existing App</div>
              <ol className="setup-steps">
                <li>Go to <a href="https://developer.spotify.com/dashboard" target="_blank" rel="noreferrer">Spotify Developer Dashboard</a></li>
                <li>Click your existing app → <strong>"Edit Settings"</strong></li>
                <li>Under <strong>Redirect URIs</strong>, add: <code>{window.location.origin}</code></li>
                <li>Click <strong>Save</strong></li>
                <li>Copy your <strong>Client ID</strong> from the app overview and paste below</li>
              </ol>
            </div>
          </div>

          <div className="setup-note">
            💡 <strong>Tip:</strong> If Spotify rejects <code>http://</code>, the app is already running on <code>https://</code> — just make sure your redirect URI matches exactly what's in your address bar.
          </div>

          <div style={{ display: 'flex', gap: '0.5rem', marginTop: '1.25rem' }}>
            <input
              name="clientId"
              placeholder="Paste your Spotify Client ID here"
              className="btn"
              style={{ background: 'var(--glass)', border: '1px solid var(--glass-border)', color: 'white', flex: 1, fontFamily: 'monospace', letterSpacing: '0.02em' }}
            />
            <button type="submit" className="btn btn-primary">Connect →</button>
          </div>
        </form>
      ) : !token ? (
        <div style={{ textAlign: 'center', maxWidth: 520, margin: '0 auto' }}>
          {/* Show exact redirect URI so user can match it in Spotify dashboard */}
          <div className="redirect-debug">
            <div className="redirect-debug-label">🔗 Redirect URI being sent to Spotify:</div>
            <div className="redirect-debug-uri">
              <code>{window.location.origin}</code>
              <button
                className="copy-btn"
                onClick={() => navigator.clipboard.writeText(window.location.origin)}
                title="Copy to clipboard"
              >📋 Copy</button>
            </div>
            <div className="redirect-debug-hint">
              This must match <strong>exactly</strong> what's saved in your Spotify App's Redirect URIs — including <code>http</code> vs <code>https</code> and no trailing slash.
            </div>
          </div>

          <a
            href={`https://accounts.spotify.com/authorize?client_id=${clientId}&redirect_uri=${encodeURIComponent(window.location.origin)}&response_type=token&scope=${SCOPES.join("%20")}`}
            className="btn btn-spotify"
            style={{ display: 'inline-flex', margin: '1rem auto 0.5rem' }}
          >
            Login to Spotify
          </a>
          <div>
            <button onClick={resetConfig} className="btn" style={{ background: 'transparent', color: 'var(--text-muted)', fontSize: '0.85rem' }}>
              Use different Client ID
            </button>
          </div>
        </div>
      ) : (
        <div style={{ display: 'flex', gap: '0.75rem', flexWrap: 'wrap', justifyContent: 'center', alignItems: 'center' }}>
          <span style={{ color: '#1DB954', fontWeight: 700, display: 'flex', alignItems: 'center', gap: '0.4rem' }}>
            ✓ Connected{spotifyUser ? ` as ${spotifyUser.name}` : ' to Spotify'}
          </span>
          {playlistUrl && (
            <a href={playlistUrl} target="_blank" rel="noreferrer" className="btn btn-spotify" style={{ fontSize: '0.85rem', padding: '0.5rem 1rem' }}>
              🎵 Open Last Playlist
            </a>
          )}
          <button onClick={logout} className="btn">Logout</button>
          <button onClick={resetConfig} className="btn" style={{ background: 'transparent', color: 'var(--text-muted)' }}>Reset Config</button>
        </div>
      )}
    </div>
  )

  return (
    <div className="container">
      <header>
        <h1>MusicFinder</h1>
        <p className="subtitle">From Critique to Collection — curating your library from the critics you trust.</p>
      </header>

      {spotifyAuthSection}

      <div className="tab-bar">
        <button
          className={`tab-btn ${activeTab === 'list' ? 'active' : ''}`}
          onClick={() => setActiveTab('list')}
        >
          📋 Spectrum Pulse Top 50
        </button>
        <button
          className={`tab-btn ${activeTab === 'parse' ? 'active' : ''}`}
          onClick={() => setActiveTab('parse')}
        >
          🎬 Parse a Video / URL
        </button>
      </div>

      {activeTab === 'list' && (
        <>
          {token && (
            <div style={{ textAlign: 'center', marginBottom: '2rem' }}>
              <button onClick={() => createPlaylist(defaultAlbums)} className="btn btn-primary">
                🎵 Create Playlist from Top 50
              </button>
            </div>
          )}
          <div className="album-grid">
            {defaultAlbums.map((item) => (
              <div key={item.rank} className="album-card">
                <div className="rank">#{item.rank}</div>
                <div className="album-info">
                  <div className="artist-name">{item.artist}</div>
                  <h2 className="album-title">{item.album}</h2>
                </div>
              </div>
            ))}
          </div>
        </>
      )}

      {activeTab === 'parse' && (
        <VideoParser
          token={token}
          onAlbumsFound={(found) => setParsedAlbums(found)}
        />
      )}

      {loading && (
        <div className="loading-overlay">
          <div className="spinner"></div>
          <h2 style={{ marginTop: '2rem' }}>{status}</h2>
          <div className="progress-bar">
            <div className="progress-fill" style={{ width: `${progress}%` }}></div>
          </div>
        </div>
      )}
    </div>
  )
}

export default App
