import { useState, useEffect } from 'react'
import defaultAlbums from './data'
import VideoParser from './VideoParser'
import './index.css'

const AUTH_ENDPOINT = "https://accounts.spotify.com/authorize"
const SCOPES = ["playlist-modify-private", "playlist-modify-public"]

function App() {
  const [token, setToken] = useState("")
  const [clientId, setClientId] = useState(window.localStorage.getItem("spotify_client_id") || "")
  const [loading, setLoading] = useState(false)
  const [progress, setProgress] = useState(0)
  const [status, setStatus] = useState("")
  const [activeTab, setActiveTab] = useState('list')  // 'list' | 'parse'
  const [parsedAlbums, setParsedAlbums] = useState([])

  useEffect(() => {
    const hash = window.location.hash
    let storedToken = window.localStorage.getItem("token")

    if (!storedToken && hash) {
      const tokenParam = hash.substring(1).split("&").find(elem => elem.startsWith("access_token"))
      if (tokenParam) {
        storedToken = tokenParam.split("=")[1]
        window.location.hash = ""
        window.localStorage.setItem("token", storedToken)
      }
    }

    setToken(storedToken || "")
  }, [])

  const saveClientId = (e) => {
    e.preventDefault()
    const id = e.target.clientId.value.trim()
    if (id) {
      setClientId(id)
      window.localStorage.setItem("spotify_client_id", id)
    }
  }

  const logout = () => {
    setToken("")
    window.localStorage.removeItem("token")
  }

  const resetConfig = () => {
    logout()
    setClientId("")
    window.localStorage.removeItem("spotify_client_id")
  }

  const createPlaylist = async (albumList, playlistName = "Spectrum Pulse: Top 50 Albums of 2025") => {
    if (!token) return
    setLoading(true)
    setProgress(0)
    setStatus("Fetching user data...")

    try {
      const userRes = await fetch("https://api.spotify.com/v1/me", {
        headers: { Authorization: `Bearer ${token}` }
      })
      const user = await userRes.json()

      const trackUris = []
      for (let i = 0; i < albumList.length; i++) {
        const { artist, album, rank } = albumList[i]
        setStatus(`Searching: "${album}" by ${artist}`)

        const searchRes = await fetch(
          `https://api.spotify.com/v1/search?q=album:${encodeURIComponent(album)}%20artist:${encodeURIComponent(artist)}&type=album&limit=1`,
          { headers: { Authorization: `Bearer ${token}` } }
        )
        const searchData = await searchRes.json()

        if (searchData.albums?.items?.length > 0) {
          const albumId = searchData.albums.items[0].id
          const tracksRes = await fetch(`https://api.spotify.com/v1/albums/${albumId}/tracks?limit=1`, {
            headers: { Authorization: `Bearer ${token}` }
          })
          const tracksData = await tracksRes.json()
          if (tracksData.items?.length > 0) {
            trackUris.push(tracksData.items[0].uri)
          }
        }

        setProgress(((i + 1) / albumList.length) * 80)
      }

      setStatus("Creating playlist...")
      const playlistRes = await fetch(`https://api.spotify.com/v1/users/${user.id}/playlists`, {
        method: "POST",
        headers: { Authorization: `Bearer ${token}`, "Content-Type": "application/json" },
        body: JSON.stringify({
          name: playlistName,
          description: "Generated by MusicFinder — first track of each album.",
          public: false
        })
      })
      const playlist = await playlistRes.json()

      setStatus("Adding tracks...")
      await fetch(`https://api.spotify.com/v1/playlists/${playlist.id}/tracks`, {
        method: "POST",
        headers: { Authorization: `Bearer ${token}`, "Content-Type": "application/json" },
        body: JSON.stringify({ uris: trackUris })
      })

      setProgress(100)
      setStatus("Playlist Created! 🎉")
      setTimeout(() => setLoading(false), 2000)
      alert(`Playlist created with ${trackUris.length} tracks!`)
    } catch (err) {
      console.error(err)
      alert("Error creating playlist. Your token may have expired — please log out and back in.")
      setLoading(false)
    }
  }

  const spotifyAuthSection = (
    <div className="actions">
      {!clientId ? (
        <form className="config-form" onSubmit={saveClientId}>
          <h3>Spotify Configuration</h3>
          <p>1. Go to <a href="https://developer.spotify.com/dashboard" target="_blank" rel="noreferrer">Spotify Developer Dashboard</a></p>
          <p>2. Create an App and add <code>{window.location.origin}</code> to Redirect URIs</p>
          <p>3. Copy your Client ID and paste below:</p>
          <div style={{ display: 'flex', gap: '0.5rem', marginTop: '1rem' }}>
            <input name="clientId" placeholder="Enter Spotify Client ID" className="btn" style={{ background: 'var(--glass)', border: '1px solid var(--glass-border)', color: 'white', flex: 1 }} />
            <button type="submit" className="btn btn-primary">Save &amp; Continue</button>
          </div>
        </form>
      ) : !token ? (
        <div style={{ textAlign: 'center' }}>
          <a
            href={`https://accounts.spotify.com/authorize?client_id=${clientId}&redirect_uri=${window.location.origin}&response_type=token&scope=${SCOPES.join("%20")}`}
            className="btn btn-spotify"
          >
            Login to Spotify
          </a>
          <button onClick={resetConfig} className="btn" style={{ marginTop: '1rem', display: 'block', margin: '0.5rem auto 0', background: 'transparent', color: 'var(--text-muted)' }}>Use different Client ID</button>
        </div>
      ) : (
        <div style={{ display: 'flex', gap: '0.75rem', flexWrap: 'wrap', justifyContent: 'center' }}>
          <span style={{ color: '#1DB954', fontWeight: 700, display: 'flex', alignItems: 'center', gap: '0.4rem' }}>✓ Connected to Spotify</span>
          <button onClick={logout} className="btn">Logout</button>
          <button onClick={resetConfig} className="btn" style={{ background: 'transparent', color: 'var(--text-muted)' }}>Reset Config</button>
        </div>
      )}
    </div>
  )

  return (
    <div className="container">
      <header>
        <h1>MusicFinder</h1>
        <p className="subtitle">From Critique to Collection — curating your library from the critics you trust.</p>
      </header>

      {spotifyAuthSection}

      <div className="tab-bar">
        <button
          className={`tab-btn ${activeTab === 'list' ? 'active' : ''}`}
          onClick={() => setActiveTab('list')}
        >
          📋 Spectrum Pulse Top 50
        </button>
        <button
          className={`tab-btn ${activeTab === 'parse' ? 'active' : ''}`}
          onClick={() => setActiveTab('parse')}
        >
          🎬 Parse a Video / URL
        </button>
      </div>

      {activeTab === 'list' && (
        <>
          {token && (
            <div style={{ textAlign: 'center', marginBottom: '2rem' }}>
              <button onClick={() => createPlaylist(defaultAlbums)} className="btn btn-primary">
                🎵 Create Playlist from Top 50
              </button>
            </div>
          )}
          <div className="album-grid">
            {defaultAlbums.map((item) => (
              <div key={item.rank} className="album-card">
                <div className="rank">#{item.rank}</div>
                <div className="album-info">
                  <div className="artist-name">{item.artist}</div>
                  <h2 className="album-title">{item.album}</h2>
                </div>
              </div>
            ))}
          </div>
        </>
      )}

      {activeTab === 'parse' && (
        <VideoParser
          token={token}
          onAlbumsFound={(found) => setParsedAlbums(found)}
        />
      )}

      {loading && (
        <div className="loading-overlay">
          <div className="spinner"></div>
          <h2 style={{ marginTop: '2rem' }}>{status}</h2>
          <div className="progress-bar">
            <div className="progress-fill" style={{ width: `${progress}%` }}></div>
          </div>
        </div>
      )}
    </div>
  )
}

export default App
