const albums = [
  { rank: 1, artist: "seeming", album: "the world" },
  { rank: 2, artist: "mckinley dixon", album: "magic, alive!" },
  { rank: 3, artist: "caroline spence", album: "heart go wild" },
  { rank: 4, artist: "cole chaney", album: "in the shadow of the mountain" },
  { rank: 5, artist: "billy woods", album: "golliwog" },
  { rank: 6, artist: "neko case", album: "neon grey midnight green" },
  { rank: 7, artist: "moron police", album: "pachinko" },
  { rank: 8, artist: "nourished by time", album: "the passionate ones" },
  { rank: 9, artist: "saor", album: "amidst the ruins" },
  { rank: 10, artist: "open mike eagle", album: "neighborhood gods unlimited" },
  { rank: 11, artist: "jason isbell", album: "foxes in the snow" },
  { rank: 12, artist: "backxwash", album: "only dust remains" },
  { rank: 13, artist: "jesse welles", album: "middle" },
  { rank: 14, artist: "charles kelley", album: "songs for a new moon" },
  { rank: 15, artist: "la dispute", album: "no one was driving the car" },
  { rank: 16, artist: "willi carlisle", album: "winged victory" },
  { rank: 17, artist: "aesop rock", album: "black hole superette" },
  { rank: 18, artist: "cmat", album: "euro-country" },
  { rank: 19, artist: "floodlights", album: "underneath" },
  { rank: 20, artist: "saba & No ID", album: "from the private collection of saba & no id" },
  { rank: 21, artist: "ruston kelly", album: "pale, through the window" },
  { rank: 22, artist: "baths", album: "gut" },
  { rank: 23, artist: "rosalia", album: "lux" },
  { rank: 24, artist: "perrie", album: "perrie" },
  { rank: 25, artist: "premrock", album: "did you enjoy your time here?" },
  { rank: 26, artist: "jid", album: "god does like ugly" },
  { rank: 27, artist: "little simz", album: "lotus" },
  { rank: 28, artist: "clipping.", album: "dead channel sky" },
  { rank: 29, artist: "256pi", album: "real life and postcard usage" },
  { rank: 30, artist: "james mcmurtry", album: "the black dog and the wandering boy" },
  { rank: 31, artist: "turnpike troubadours", album: "the price of admission" },
  { rank: 32, artist: "redveil", album: "sankofa" },
  { rank: 33, artist: "hayden pedigo", album: "i’ll be waving as you drive away" },
  { rank: 34, artist: "agriculture", album: "the spiritual sound" },
  { rank: 35, artist: "florence + The machine", album: "everybody scream" },
  { rank: 36, artist: "clipse", album: "let god sort em out" },
  { rank: 37, artist: "de la soul", album: "cabin in the sky" },
  { rank: 38, artist: "amanda shires", album: "nobody’s girl" },
  { rank: 39, artist: "deafheaven", album: "ordinary people with power" },
  { rank: 40, artist: "jesse welles", album: "pilgrim" },
  { rank: 41, artist: "sombr", album: "I barely know her" },
  { rank: 42, artist: "flummox", album: "southern progress" },
  { rank: 43, artist: "perfume genius", album: "glory" },
  { rank: 44, artist: "unreqvited", album: "a pathway to the moon" },
  { rank: 45, artist: "khamari", album: "to dry a tear" },
  { rank: 46, artist: "ethel cain", album: "perverts" },
  { rank: 47, artist: "r.a.p. ferreira & kenny segal", album: "the night green side of it" },
  { rank: 48, artist: "lucy dacus", album: "forever is a feeling" },
  { rank: 49, artist: "bruiser wolf", album: "potluck" },
  { rank: 50, artist: "the weather station", album: "Humanhood" }
];

export default albums;
